name: Deploy to cPanel (FTPS)

on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:

jobs:
  web-deploy:
    name: Deploy to cPanel
    runs-on: ubuntu-latest

    steps:
      - name: Get latest code
        uses: actions/checkout@v4

      - name: Setup PHP 8.3
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3

      - name: Install Composer dependencies
        run: composer install --no-dev --no-interaction --prefer-dist --optimize-autoloader


      - name: Deploy via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.SERVER }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          protocol: ftps
          port: 21
          server-dir: /
          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/**
            .env
            .github/
            tests/
            storage/framework/cache/**
            storage/framework/sessions/**
            storage/framework/views/**
            storage/logs/*.log
